name: base
channels:
  - local
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - attrs=20.3.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.9.3=pyha847dfd_0
  - blas=1.0=openblas
  - blosc=1.20.1=hd408876_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.10.14=0
  - catalogue=1.0.0=py38_1
  - certifi=2020.6.20=py38_0
  - cffi=1.14.3=py38h261ae71_2
  - chardet=3.0.4=py38h06a4308_1003
  - cloudpickle=1.6.0=py_0
  - cmake=3.19.6=h973ab73_0
  - conda=4.11.0=py38h06a4308_0
  - conda-build=3.21.4=py38h06a4308_0
  - conda-package-handling=1.7.2=py38h03888b9_0
  - cryptography=3.2.1=py38h3c74f83_1
  - cymem=2.0.5=py38h2531618_0
  - cython-blis=0.7.4=py38h27cfd23_1
  - cytoolz=0.11.0=py38h7b6447c_0
  - dask-core=2021.7.2=pyhd3eb1b0_0
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.0.6=pyhd3eb1b0_0
  - expat=2.3.0=h2531618_2
  - filelock=3.0.12=pyhd3eb1b0_1
  - fontconfig=2.13.1=hba837de_1005
  - freetype=2.10.4=h5ab3b9f_0
  - fsspec=2021.7.0=pyhd3eb1b0_0
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.68.3=h9c3ff4c_0
  - glib-tools=2.68.3=h9c3ff4c_0
  - glob2=0.7=pyhd3eb1b0_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py38h06a4308_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.2.0=h06a4308_610
  - ipython=7.22.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.0=py38_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.2=py38_0
  - kiwisolver=1.3.1=py38h2531618_0
  - krb5=1.18.2=h173b8e3_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libarchive=3.4.2=h62408e4_0
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglib=2.68.3=h3e27bee_0
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h516909a_0
  - liblief=0.10.1=he6710b0_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libopenblas=0.3.10=h5a2b251_0
  - libpng=1.6.37=hbc83047_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtiff=4.2.0=h85742a9_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.10=hb55368b_3
  - llvmlite=0.35.0=py38h612dafd_4
  - locket=0.2.1=py38h06a4308_1
  - lz4-c=1.9.3=h2531618_0
  - lzo=2.10=h7b6447c_2
  - magma-cuda110=2.5.2=5
  - markupsafe=1.1.1=py38h7b6447c_0
  - matplotlib=3.4.1=py38h578d9bd_0
  - matplotlib-base=3.4.1=py38hcc49a3a_0
  - mkl=2019.4=243
  - mkl-include=2019.4=243
  - mock=4.0.3=pyhd3eb1b0_0
  - murmurhash=1.0.5=py38h2531618_0
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.2=hff7bd54_1
  - nomkl=3.0=0
  - numba=0.52.0=py38ha9443f7_0
  - numexpr=2.7.1=py38h7ea95a0_0
  - numpy=1.20.1=py38h5a90a98_0
  - numpy-base=1.20.1=py38h34387ca_0
  - olefile=0.46=py_0
  - openblas=0.3.10=0
  - openblas-devel=0.3.10=0
  - openjpeg=2.3.0=h05c96fa_1
  - openssl=1.1.1m=h7f8727e_0
  - parso=0.8.2=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_0
  - patchelf=0.12=h2531618_1
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py38h2c7a002_0
  - pip=20.2.4=py38h06a4308_0
  - pkginfo=1.7.0=py38h06a4308_0
  - plac=1.1.0=py38_1
  - preshed=3.0.2=py38he6710b0_1
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - psutil=5.8.0=py38h27cfd23_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-lief=0.10.1=py38h403a769_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pygments=2.8.1=pyhd3eb1b0_0
  - pyopenssl=19.1.0=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.17.3=py38h7b6447c_0
  - pysocks=1.7.1=py38h06a4308_0
  - pytables=3.6.1=py38h9fd0a39_0
  - python=3.8.8=hdb3f193_4
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python_abi=3.8=2_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38h7b6447c_2
  - pyyaml=5.4.1=py38h27cfd23_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - rhash=1.4.1=h3c74f83_1
  - ripgrep=12.1.1=0
  - ruamel_yaml=0.15.87=py38h7b6447c_1
  - scipy=1.6.2=py38hf56f3a7_1
  - setuptools=50.3.1=py38h06a4308_1
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py38h06a4308_0
  - soupsieve=2.2.1=pyhd3eb1b0_0
  - spacy=2.3.5=py38hff7bd54_0
  - sqlite=3.33.0=h62c20be_0
  - srsly=1.0.5=py38h2531618_0
  - tbb=2020.3=hfd86e86_0
  - thinc=7.4.5=py38h9a67853_0
  - tifffile=2020.10.1=py38hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - urllib3=1.25.11=py_0
  - wasabi=0.8.2=pyhd3eb1b0_0
  - wcwidth=0.2.5=py_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.4.1=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.12.0
    - alabaster==0.7.12
    - apex==0.1
    - appdirs==1.4.4
    - argon2-cffi==20.1.0
    - ascii-graph==1.5.1
    - async-generator==1.10
    - audioread==2.1.9
    - autopep8==1.5.7
    - babel==2.9.1
    - bleach==3.3.0
    - boto3==1.17.60
    - botocore==1.20.60
    - cachetools==4.2.2
    - click==7.1.2
    - codecov==2.1.11
    - coverage==5.5
    - cxxfilt==0.2.2
    - cycler==0.10.0
    - cython==0.28.4
    - dataproperty==0.50.1
    - defusedxml==0.7.1
    - dllogger==0.1.0
    - docutils==0.16
    - entrypoints==0.3
    - flake8==3.7.9
    - flask==1.1.2
    - future==0.18.2
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.5
    - graphsurgeon==0.4.5
    - grpcio==1.37.0
    - h5py==3.2.1
    - html2text==2020.1.16
    - hypothesis==4.50.8
    - imagesize==1.2.0
    - inflect==5.3.0
    - iniconfig==1.1.1
    - ipdb==0.13.7
    - ipykernel==5.5.3
    - itsdangerous==1.1.0
    - jmespath==0.10.0
    - joblib==1.0.1
    - json5==0.9.5
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyter-tensorboard==0.2.0
    - jupyterlab==2.3.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==1.2.0
    - jupytext==1.11.1
    - librosa==0.8.0
    - lmdb==1.2.1
    - mako==1.1.4
    - markdown==3.3.4
    - markdown-it-py==0.6.2
    - maskrcnn-benchmark==0.1
    - mbstrdecoder==1.0.1
    - mccabe==0.6.1
    - mdit-py-plugins==0.2.6
    - mistune==0.8.4
    - mlperf-compliance==0.0.10
    - msgfy==0.1.0
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - networkx==2.0
    - nltk==3.6.2
    - notebook==6.2.0
    - nvidia-dali-cuda110==1.0.0
    - nvidia-dlprof-pytorch-nvtx==1.1.0
    - nvidia-pyprof==3.10.0
    - oauthlib==3.1.1
    - onnx==1.8.0
    - onnxruntime==1.7.0
    - packaging==20.9
    - pandas==1.1.4
    - pandocfilters==1.4.3
    - pathvalidate==2.4.1
    - pillow-simd==7.0.0.post3
    - pluggy==0.13.1
    - polygraphy==0.29.1
    - pooch==1.3.0
    - prettytable==2.1.0
    - progressbar==2.5
    - prometheus-client==0.10.1
    - protobuf==3.15.8
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.6.2
    - pycocotools==2.0+nv0.5.1
    - pycodestyle==2.7.0
    - pycuda==2020.1
    - pydot==1.4.2
    - pyflakes==2.1.1
    - pynvml==8.0.4
    - pytablewriter==0.47.0
    - pytest==6.2.3
    - pytest-cov==2.11.1
    - pytest-pythonpath==0.7.3
    - python-dateutil==2.8.1
    - python-hostlist==1.21
    - python-nvd3==0.15.0
    - python-slugify==4.0.1
    - pytools==2021.2.6
    - pytorch-quantization==2.1.0
    - pytorch-transformers==1.1.0
    - pyzmq==22.0.3
    - regex==2021.4.4
    - requests-oauthlib==1.3.0
    - resampy==0.2.2
    - revtok==0.0.3
    - rsa==4.7.2
    - s3transfer==0.4.2
    - sacrebleu==1.2.10
    - sacremoses==0.0.35
    - scikit-image==0.15.0
    - scikit-learn==0.24.2
    - send2trash==1.5.0
    - sentencepiece==0.1.95
    - shapely==1.7.1
    - snowballstemmer==2.1.0
    - soundfile==0.10.3.post1
    - sox==1.4.1
    - sphinx==3.5.4
    - sphinx-glpi-theme==0.3
    - sphinx-rtd-theme==0.5.2
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - subword-nmt==0.3.3
    - tabledata==1.1.3
    - tabulate==0.8.9
    - tensorboard==2.6.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorrt==7.2.3.4
    - terminado==0.9.4
    - testpath==0.4.4
    - text-unidecode==1.3
    - threadpoolctl==2.1.0
    - toml==0.10.2
    - torch==1.9.0a0+2ecb2c7
    - torchtext==0.10.0a0
    - torchvision==0.9.0a0
    - tqdm==4.53.0
    - typepy==1.1.5
    - typing-extensions==3.7.4.3
    - uff==0.6.9
    - unidecode==1.2.0
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - wrapt==1.10.11
    - yacs==0.1.8
